### ISSUE TITLE
App causing errors downstream (error about location.long size)

### ISSUE THREAD

**Issue by aklohr** [movestore/thinData-byTime#5]
Hi, I'm trying to run a workflow (see screenshot) where I filter to weekly locations using the _move2_ version of the Thin Data by Time App, however regardless of whether I select 1 week or 1 hour it is causing the apps downstream to throw errors (screenshots below). Something to do with the location.long attribute...could this be a bug in the output the app passes along? When I remove the Time app all of the other apps run just fine.

I'm using 5 elk from the public study "Ya Ha Tinda elk project, Banff National Park, 2001-2023 (females)"; let me know if you'd like me to share my workflow.

**Workflow**
![image](https://github.com/movestore/thinData-byTime/assets/112666849/abc0323a-7552-4572-848f-1dce86abcd5a)

**Track Summary Statistics error message**
![image](https://github.com/movestore/thinData-byTime/assets/112666849/ce4cb1d5-3754-420e-8a8e-6e0c91db6e10)

**Logs from Summary Stats app**
![image](https://github.com/movestore/thinData-byTime/assets/112666849/87590c82-a388-4dde-8653-b6934dc935b3)

**Home Range error message**
![image](https://github.com/movestore/thinData-byTime/assets/112666849/6ede0880-f0dd-4b8c-bedb-18bf3d96c4cd)

**Logs from Home Range (Kernel UD) app**
![image](https://github.com/movestore/thinData-byTime/assets/112666849/0462dede-0c4e-4036-806e-43f8b71a1cd2)

**Comment by annescharf** [comment]
Hi @aklohr there has been a change in the move2 package that might be causing that this app causes all these errors. I'll look into it and try to fix it asap

**Comment by andreakoelzsch** [comment]
@aklohr @annescharf FYI, the Chloe has updated the Home Range App and reports that is shall now work togehter with the thin data by time App. Hope this helps

**Comment by annescharf** [comment]
@aklohr I found the bug in the thin data by time app. now all seems to work
